In [1]:
import pandas as pd
import json

In [4]:
request = open("cities.json")
data = json.load (request)
df = pd.DataFrame(data)
df

                    city country  pop2023  latitude  longitude     fill
0                Toronto  Canada  2600000   43.7001   -79.4163  #3288bd
1               Montreal  Canada  1600000   45.5088   -73.5878  #99d594
2                Calgary  Canada  1019942   51.0501  -114.0850  #99d594
3                 Ottawa  Canada   812129   45.4112   -75.6981  #e6f598
4               Edmonton  Canada   712391   53.5501  -113.4690  #ffffbf
..                   ...     ...      ...       ...        ...      ...
395  Etobicoke West Mall  Canada    11848   43.6464   -79.5698      NaN
396       Yonge-Eglinton  Canada    11817   43.7047   -79.4036      NaN
397       Dufferin Grove  Canada    11785   43.6577   -79.4279      NaN
398            Montmagny  Canada    11724   46.9804   -70.5549      NaN
399               Gander  Canada    11688   48.9562   -54.6165      NaN

[400 rows x 6 columns]

In [5]:
df.to_csv("cities.csv")